back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    name = db.Column(db.String(25),primary_key=True)
    password = db.Column(db.String(255),nullable=False)
    number = db.Column(db.String(25),nullable=False)
    email = db.Column(db.String(25),nullable=False)
    create_time = db.Column(db.DateTime,default=datetime.now)

    __tablename__ = 'yh'

    #保存功能
    def save(self):
        db.session.add(self)
        db.session.commit()


class LanMu(db.Model):
    id = db.Column(db.String(30),primary_key=True)
    bieming = db.Column(db.String(30), nullable=False)
    gjz = db.Column(db.String(50),nullable=False)
    miaoshu = db.Column(db.TEXT,nullable=False)
    __tablename__ = 'lanmu'


class WZ(db.Model):
    title = db.Column(db.String(50),primary_key=True)
    nr = db.Column(db.TEXT,nullable=False)
    ms = db.Column(db.TEXT,nullable=False)
    __tablename__ = 'wenzhang'

back/views.py
from flask import Blueprint, request, render_template, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash


#验证密码的 jianjiatow

#第一步生成蓝图，用于管理路由
from back.models import User, LanMu, db, WZ
from utils.functions import is_login

back_blue = Blueprint('back',__name__)

#第二步 ： 使用蓝图对象管理路由

#首页
@back_blue.route('/',methods=['GET','POST'])
def home():
    if request.method =='GET':
        return render_template('back/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        print(username,password)
        user = User.query.filter(User.name == username).first()
        if not user:
            error = '用户名不存在'
            return render_template('back/login.html',error=error)
        if not check_password_hash(user.password, password):
            error = '密码错误'
            return render_template('back/login.html',error=error)
        session['user_id'] = user.name
        return redirect(url_for('back.index'))

#注册
@back_blue.route('/register/',methods=['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        #获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        password1 = request.form.get('password1')
        number = request.form.get('number')
        email = request.form.get('email')
        # 判断用户名是否注册过，如果注册在判断密码
        user = User.query.filter(User.name == username).first()
        if user:
            #用户存在
            error = '用户名已存在'
            return render_template('back/register.html', error = error)
        else:
            if password1 == password:
                #保存数据
                user = User()
                user.name = username
                # user.password = password
                #给密码编码
                user.password = generate_password_hash(password)
                user.email = email
                user.number = number
                user.save()
                return redirect(url_for('back.home'))
            else:
                #密码不一样
                error='两次输入的密码不一致'
                return render_template('back/register.html',error=error)

#得到博客主页
@back_blue.route('/index/',methods=['GET'])
@is_login
def index():
    if request.method == 'GET':
        return render_template('back/index.html', error=session.get('user_id'))


@back_blue.route('/delete/',methods=['GET'])
def delete():
    if request.method == 'GET':
        session.pop('user_id')  #删除session
        return redirect(url_for('back.home'))


@back_blue.route('/wenzhang/',methods=['GET','POST'])
@is_login
def wenzhang():
    if request.method == 'GET':
        types = WZ.query.all()
        return render_template('back/add-article.html',error=session.get('user_id'), types=types)
    if request.method == 'POST':
        title = request.form.get('title')
        nr = request.form.get('nr')
        ms = request.form.get('ms')
        if not (title and nr and ms):
            errtr = '请完整输入'
            return render_template('back/add-article.html', errtr=errtr)
        else:
            w = WZ()
            w.title = title
            w.nr = nr
            w.ms = ms
            db.session.add(w)
            db.session.commit()
            return redirect(url_for('back.wenzhang'))



@back_blue.route('/gonggao/',methods=['GET'])
@is_login
def gonggao():
    if request.method == 'GET':
        return render_template('back/add-notice.html',error=session.get('user_id'))


@back_blue.route('/pinglun/',methods=['GET'])
@is_login
def pinglun():
    if request.method == 'GET':
        return render_template('back/comment.html',error=session.get('user_id'))

#栏目的添加
@back_blue.route('/lanmu/',methods=['GET','POST'])
@is_login
def lanmu():
    if request.method == 'GET':
        types = LanMu.query.all()
        return render_template('back/category.html', error=session.get('user_id'),types=types)
    if request.method =='POST':
        name = request.form.get('name')
        bm = request.form.get('bm')
        gjz = request.form.get('gjz')
        ms = request.form.get('ms')
        #保存栏目信息
        LM = LanMu()
        LM.id = name
        LM.bieming = bm
        LM.gjz = gjz
        LM.miaoshu = ms
        db.session.add(LM)
        db.session.commit()
        return redirect(url_for('back.lanmu'))

#栏目删除
@is_login
@back_blue.route('/del_lanmu/<string:id>/',methods=['GET'])
def del_type(id):
    #从数据库里找到id一样的一行完整数据，
    atype = LanMu.query.get(id)
    db.session.delete(atype) #删除
    db.session.commit()
    return redirect(url_for('back.lanmu'))


@is_login
@back_blue.route('/xiugai/<string:id>',methods=['GET','POST'])

def undate_lanmu(id):
    if request.method == 'GET':
        return render_template('back/xiugai.html')
    if request.method == 'POST':
        name = request.form.get('name')
        bm = request.form.get('bm')
        gjz = request.form.get('gjz')
        ms = request.form.get('ms')
        #从数据库里找到id一样的一行数据
        atype = LanMu.query.get(id)
        # print(atype)
        atype.id = name
        atype.bieming = bm
        atype.gjz = gjz
        atype.miaoshu = ms
        #添加  提交
        db.session.add(atype)
        db.session.commit()
        return redirect(url_for('back.lanmu'))

web/views.py
from flask import Blueprint, request,\
    render_template, redirect, url_for

#第一步 ：生成蓝图对象
#蓝图用于管理路由
web_blue = Blueprint('first', __name__)



@web_blue.route('/' , methods=['GET'])
def shouye():
    if request.method == 'GET':
        return render_template('web/index.html')


@web_blue.route('/about/',methods=['GET'])
def one():
    if request.method == 'GET':
        return render_template('web/about.html')

@web_blue.route('/share/',methods=['GET'])
def two():
    if request.method == 'GET':
        return render_template('web/share.html')

@web_blue.route('/leixing/',methods=['GET'])
def three():
    if request.method == 'GET':
        return render_template('web/list.html')

@web_blue.route('/fanju/',methods=['GET'])
def four():
    if request.method == 'GET':
        return render_template('web/life.html')

@web_blue.route('/shenzuo/',methods=['GET'])
def five():
    if request.method == 'GET':
        return render_template('web/time.html')


@web_blue.route('/liuyan/',methods=['GET'])
def six():
    if request.method == 'GET':
        return render_template('web/gbook.html')

@web_blue.route('/neirong/',methods=['GET'])
def server():
    if request.method == 'GET':
        return render_template('web/info.html')

templates/back/base.html
{{ ex}}

templates/back/login.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>博客后台管理</title>
  <link href="{{ url_for('static',filename='bk/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static',filename='bk/css/style.css')}}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static',filename='bk/css/login.css')}}"rel="stylesheet" type="text/css" >
  <link href="{{ url_for('static',filename='bk/images/icon/icon.png')}}"rel="stylesheet" type="text/css">
  <link href="{{ url_for('static',filename='bk/images/icon/favicon.ico')}}"rel="stylesheet" type="text/css">
  <script src="{{ url_for('static',filename='bk/js/jquery-2.1.4.min.js')}}"></script>
</head>
<body class="user-select">
<div class="container">
  <div class="siteIcon"><img src="../static/bk/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="动漫博客网" draggable="false" /></div>

  <form action="/back/" method="post" autocomplete="off" class="form-signin">
    <h2 class="form-signin-heading">管理员登录</h2>
    {{error}}
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="password" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <a href=""><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>

  <div class="footer">
    <p>
       <a href="/back/register/" data-toggle="tooltip" data-placement="left" title="注册">⬅注册</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="{{ url_for('first.shouye')}}" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">跳转前台 ➡</a></p>
  </div>
</div>
<script src="{{ url_for('static',filename='js/bootstrap.min.js')}}"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
</html>

templates/web/about.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title> 一个热爱篮球的大男孩 </title>

<link href="{{ url_for('static',filename='css/base.css')}}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/index.css')}}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/m.css')}}" rel="stylesheet">
<script src="{{ url_for('static',filename='js/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{ url_for('static',filename='js/jquery.easyfader.min.js')}}"></script>
<script src="{{ url_for('static',filename='js/scrollReveal.js')}}"></script>
<script src="{{ url_for('static',filename='js/common.js')}}"></script>

</head>
<body>
<header>
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="{{ url_for('first.shouye')}}">我的篮球公园</a></h1>
      <li><a href="{{ url_for('first.shouye')}}">网站首页</a> </li>
      <li><a href="{{ url_for('first.one')}}">NBA</a> </li>
      <li><a href="{{ url_for('first.two')}}">球星</a>
        <ul class="sub-nav">
          <li><a href="share">麦迪</a></li>
          <li><a href="share">科比</a></li>
          <li><a href="share">詹姆斯</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.three')}}">类型</a>
        <ul class="sub-nav">
          <li><a href="list.html">扣篮</a></li>
          <li><a href="list.html">上篮</a></li>
          <li><a href="list.html">干拔</a></li>
          <li><a href="list.html">后仰</a></li>
          <li><a href="list.html">三分</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.four')}}">生涯</a>
        <ul class="sub-nav">
          <li><a href="life.html">麦迪生涯录像</a></li>
          <li><a href="life.html">科比生涯录像</a></li>
          <li><a href="life.html">詹姆斯比赛录像</a></li>
          <li><a href="life.html">夺冠之路</a></li>
        </ul>
       <li><a href="{{ url_for('first.five')}}">高光时刻</a> </li>
      <li><a href="{{ url_for('first.six')}}">留言</a> </li>
      <li><a href="{{ url_for('first.server')}}">内容</a> </li>
    </nav>
</header>

<div class="pagebg ab"> </div>
<div class="container">
  <h1 class="t_nav"><span>像“草根”一样，紧贴着地面，低调的存在，冬去春来，枯荣无恙。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">关于我</a></h1>
  <div class="news_infos">
    <ul>
      <p>我的篮球公园   球迷聚集地<br />
        <br />天妒奇才 特雷西-麦克格雷迪<br />
        <br />科比_布莱恩特<br />
        <br />勒布朗-詹姆斯<br />
        <br />我就想麦迪可以拿一个冠军啊</p>你知道他背后有多努力吗？</p>真的是!</p>黑曼巴</p>

      <br />
      <h2>About my blog</h2>
      &nbsp;
      <p>域 名：www.xiaoyu.com 创建于2019年04月12日&nbsp;还没激活</p>
      <br />
      <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
      <br />
      <p>备案号：蜀ICP备11002373号-1</p>
      <br />
      <p>程 序：PHP 帝国CMS7.5</p>
    </ul>
  </div>
  <div class="sidebar">
    <div class="about">
      <p class="avatar"> <img src="images/avatar.jpg" alt=""> </p>
      <p class="abname">篮球公园</p>
      <p class="abposition">麦迪 科比 詹姆斯</p>
      <p class="abtext"> 小前锋 得分后卫 大中锋</p>
    </div>
    <div class="weixin">
      <h2 class="hometitle">微信关注</h2>
      <ul>
        <img src="images/wx.jpg">
      </ul>
    </div>
  </div>
</div>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">篮球公园</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

templates/web/gbook.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title> 一个热爱篮球的大男孩 </title>
<!--反向解析写法-->
  <link href="{{ url_for('static',filename='css/base.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='css/index.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='css/m.css')}}" rel="stylesheet">


  <script src="{{ url_for('static',filename='js/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/jquery.easyfader.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/scrollReveal.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/common.js')}}" type="text/javascript"></script>

</head>
<body>
<header> 
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="{{ url_for('first.shouye')}}">我的篮球公园</a></h1>
      <li><a href="{{ url_for('first.shouye')}}">网站首页</a> </li>
      <li><a href="{{ url_for('first.one')}}">NBA</a> </li>
      <li><a href="{{ url_for('first.two')}}">球星</a>
        <ul class="sub-nav">
          <li><a href="share">麦迪</a></li>
          <li><a href="share">科比</a></li>
          <li><a href="share">詹姆斯</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.three')}}">类型</a>
        <ul class="sub-nav">
          <li><a href="list.html">扣篮</a></li>
          <li><a href="list.html">上篮</a></li>
          <li><a href="list.html">干拔</a></li>
          <li><a href="list.html">后仰</a></li>
          <li><a href="list.html">三分</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.four')}}">生涯</a>
        <ul class="sub-nav">
          <li><a href="life.html">麦迪生涯录像</a></li>
          <li><a href="life.html">科比生涯录像</a></li>
          <li><a href="life.html">詹姆斯比赛录像</a></li>
          <li><a href="life.html">夺冠之路</a></li>
        </ul>
       <li><a href="{{ url_for('first.five')}}">高光时刻</a> </li>
      <li><a href="{{ url_for('first.six')}}">留言</a> </li>
      <li><a href="{{ url_for('first.server')}}">内容</a> </li>

      <!--search begin-->
      <div id="search_bar" class="search_bar">
        <form  id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title" />
          <input type="hidden" name="tempid" value="1" />
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索" />
          <span class="search_ico"></span>
        </form>
      </div>
      <!--search end--> 
    </nav>
  </div>
  <!--menu end--> 
  <!--mnav begin-->
  <div id="mnav">
    <h2><a href="http://www.yangqq.com" class="mlogo">杨青博客</a><span class="navicon"></span></h2>
    <dl class="list_dl">
      <dt class="list_dt"> <a href="index.html">网站首页</a> </dt>
      <dt class="list_dt"> <a href="about.html">关于我</a> </dt>
      <dt class="list_dt"> <a href="#">模板分享</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="share.html">个人博客模板</a></li>
          <li><a href="share.html">国外Html5模板</a></li>
          <li><a href="share.html">企业网站模板</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="#">学无止境</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="list.html">心得笔记</a></li>
          <li><a href="list.html">CSS3|Html5</a></li>
          <li><a href="list.html">网站建设</a></li>
          <li><a href="list.html">推荐工具</a></li>
          <li><a href="list.html">JS实例索引</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="#">慢生活</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="life.html">日记</a></li>
          <li><a href="life.html">欣赏</a></li>
          <li><a href="life.html">程序人生</a></li>
          <li><a href="life.html">经典语录</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="time.html">时间轴</a> </dt>
      <dt class="list_dt"> <a href="gbook.html">留言</a> </dt>
    </dl>
  </div>
  <!--mnav end--> 
</header>
<div class="pagebg ab"> </div>
<div class="container">
  <h1 class="t_nav"><span>你，我生命中一个重要的过客，我们之所以是过客，因为你未曾会为我停留。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">留言</a></h1>
  <div class="news_infos">
    <ul>
      此处安装评论插件
    </ul>
  </div>
  <div class="sidebar">
    <div class="about">
      <p class="avatar"> <img src="images/avatar.jpg" alt=""> </p>
      <p class="abname">dancesmile | 杨青</p>
      <p class="abposition">Web前端设计师、网页设计</p>
      <p class="abtext"> 一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。 </p>
    </div>
    <div class="weixin">
      <h2 class="hometitle">微信关注</h2>
      <ul>
        <img src="images/wx.jpg">
      </ul>
    </div>
  </div>
</div>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

templates/web/share.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title> 一个热爱篮球的大男孩 </title>

<link href="{{ url_for('static',filename='css/base.css')}}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/index.css')}}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/m.css')}}" rel="stylesheet">
<script src="{{ url_for('static',filename='js/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{ url_for('static',filename='js/jquery.easyfader.min.js')}}"></script>
<script src="{{ url_for('static',filename='js/scrollReveal.js')}}"></script>
<script src="{{ url_for('static',filename='js/common.js')}}"></script>

</head>
<body>
<header> 
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="{{ url_for('first.shouye')}}">我的篮球公园</a></h1>
      <li><a href="{{ url_for('first.shouye')}}">网站首页</a> </li>
      <li><a href="{{ url_for('first.one')}}">NBA</a> </li>
      <li><a href="{{ url_for('first.two')}}">球星</a>
        <ul class="sub-nav">
          <li><a href="share">麦迪</a></li>
          <li><a href="share">科比</a></li>
          <li><a href="share">詹姆斯</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.three')}}">类型</a>
        <ul class="sub-nav">
          <li><a href="list.html">扣篮</a></li>
          <li><a href="list.html">上篮</a></li>
          <li><a href="list.html">干拔</a></li>
          <li><a href="list.html">后仰</a></li>
          <li><a href="list.html">三分</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.four')}}">生涯</a>
        <ul class="sub-nav">
          <li><a href="life.html">麦迪生涯录像</a></li>
          <li><a href="life.html">科比生涯录像</a></li>
          <li><a href="life.html">詹姆斯比赛录像</a></li>
          <li><a href="life.html">夺冠之路</a></li>
        </ul>
       <li><a href="{{ url_for('first.five')}}">高光时刻</a> </li>
      <li><a href="{{ url_for('first.six')}}">留言</a> </li>
      <li><a href="{{ url_for('first.server')}}">内容</a> </li>

      <!--search begin-->
      <div id="search_bar" class="search_bar">
        <form  id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title" />
          <input type="hidden" name="tempid" value="1" />
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索" />
          <span class="search_ico"></span>
        </form>
      </div>
      <!--search end--> 
    </nav>
  </div>
  <!--menu end--> 
  <!--mnav begin-->
  <div id="mnav">
    <h2><a href="http://www.yangqq.com" class="mlogo">肖誉博客</a><span class="navicon"></span></h2>
    <dl class="list_dl">
      <dt class="list_dt"> <a href="index.html">网站首页</a> </dt>
      <dt class="list_dt"> <a href="about.html">关于我</a> </dt>
      <dt class="list_dt"> <a href="#">模板分享</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="share.html">个人博客模板</a></li>
          <li><a href="share.html">国外Html5模板</a></li>
          <li><a href="share.html">企业网站模板</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="#">学无止境</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="list.html">心得笔记</a></li>
          <li><a href="list.html">CSS3|Html5</a></li>
          <li><a href="list.html">网站建设</a></li>
          <li><a href="list.html">推荐工具</a></li>
          <li><a href="list.html">JS实例索引</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="#">慢生活</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="life.html">日记</a></li>
          <li><a href="life.html">欣赏</a></li>
          <li><a href="life.html">程序人生</a></li>
          <li><a href="life.html">经典语录</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="time.html">时间轴</a> </dt>
      <dt class="list_dt"> <a href="gbook.html">留言</a> </dt>
    </dl>
  </div>
  <!--mnav end-->
</header>
<div class="pagebg sh"></div>
<div class="container">
  <h1 class="t_nav"><span>好咖啡要和朋友一起品尝，好“模板”也要和同样喜欢它的人一起分享。 </span><a href="/" class="n1">网站首页</a><a href="/" class="n2">模板分享</a></h1>


<div class="share">
<ul>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/toppic01.jpg"></i>
      <h2><b>别让这些闹心的套路，毁了你的网页设计!</b></h2>
      <span>喜欢 | 190</span> </a></div> </li>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/toppic02.jpg"></i>
      <h2><b>陌上花开，可缓缓归矣</b></h2>
      <span>喜欢 | 190</span> </a></div> </li>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/banner01.jpg"></i>
      <h2><b>网页中图片属性固定宽度，如何用js改变大小</b></h2>
      <span>喜欢 | 190</span> </a> </div> </li>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/text01.jpg"></i>
      <h2><b>个人博客，属于我的小世界！</b></h2>
      <span>喜欢 | 190</span> </a> </div> </li>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/text02.jpg"></i>
      <h2><b>html5个人博客模板《黑色格调》</b></h2>
      <span>喜欢 | 190</span> </a> </div> </li>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/banner02.jpg"></i>
      <h2><b>帝国cms 首页或者列表无图，不使用默认图片的方法</b></h2>
      <span>喜欢 | 190</span> </a> </div> </li>
       <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/text02.jpg"></i>
      <h2><b>十条设计原则教你学会如何设计网页布局!</b></h2>
      <span>喜欢 | 190</span> </a> </div> </li>
 <li> <div class="shareli"><a href="/" target="_blank"> <i><img src="images/banner02.jpg"></i>
      <h2><b>html5个人博客模板主题《清雅》</b></h2>
      <span>喜欢 | 190</span> </a> </div> </li>
</ul>
</div>

<div class="pagelist"><a title="Total record">&nbsp;<b>45</b> </a>&nbsp;&nbsp;&nbsp;<b>1</b>&nbsp;<a href="/download/index_2.html">2</a>&nbsp;<a href="/download/index_2.html">下一页</a>&nbsp;<a href="/download/index_2.html">尾页</a></div>


</div>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">肖誉个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>